### ISSUE TITLE
Lost cursor after triggering posframe

### ISSUE THREAD

**Issue by qhuyduong** [tumashu/posframe#19]
I'm using posframe with Emacs 26.1 on Mac OS. The issue is that after calling `(posframe-show ...)`, the cursor is lost!
Hope to get the fix soon.

![screen recording 2018-11-12 at 8 34 27 pm 1 1](https://user-images.githubusercontent.com/16358771/48351624-4a074d00-e6bd-11e8-8214-59e362a78d4e.gif)

**Comment by xeals** [comment]
Also able to reproduce on Linux. The cursor gets moved to the top-left of the Emacs window.

For me the fault seems to be due to [`posframe--mouse-banish`](https://github.com/tumashu/posframe/blob/master/posframe.el#L517). The function cites an issue which doesn't really explain why the mouse needs moving.

It's supposed to be disabled on Darwin (MacOS), but might be worth checking the value of `posframe-mouse-banish` anyway to see if the issue is consistent.

**Comment by tumashu** [comment]
some WM can not do well with posframe, if mouse curse is on the top of posframe , your type will insert into posframe, so i move mouse to 0,0

**Comment by tumashu** [comment]
gnome xfce windows may not have this problem, please set posframe-mouse-banish to nil, if your WM no the problem

**Comment by qhuyduong** [comment]
@xeals @tumashu I have tried to set `posframe-mouse-banish` to nil but no luck!

**Comment by qhuyduong** [comment]
I have switched to use https://github.com/railwaycat/homebrew-emacsmacport and the issue seems to be fixed already!
