### ISSUE TITLE
usage with exwm

### ISSUE THREAD

**Issue by 11111000000** [tumashu/posframe#21]
1) Currently, posframe displays **under** xorg windows.
2) I see window blinking when posframe shown

**Comment by tumashu** [comment]
It is not possible at the moment, for child-frame of emacs is not allowed to the top of other app's window

**Comment by conao3** [comment]
Now posframe works well with exwm. And there is no blinking.
This issue could close?

**Comment by tumashu** [comment]
@conao3 really? does exwm change something?

**Comment by conao3** [comment]
Ah, sorry. This issue has remained.
Because I put other X applications in one display only and other displays show Emacs only, I hasn't faced this issue.

**Comment by clemera** [comment]
A workaround is to set `parent-frame` to `nil` in `ivy-posframe-parameters`.

**Comment by QiangF** [comment]
@tumashu Please let posframe-show returns the frame, so it is more convenient to set it's parent-frame property, which is useful for tooltip display.
There is a workaround for posframe placement on a multiple monitor setup:
https://github.com/ch11ng/exwm/issues/550

**Comment by QiangF** [comment]
If we can get the current point position in any input area of other applications, maybe we can use posframe to display the tooltip for the input method.

**Comment by tumashu** [comment]
@QiangF Fixed

**Comment by tumashu** [comment]
I try to fix exwm problem, maybe useful:
1. https://github.com/tumashu/posframe/commit/9a6bb60c55cea7627764f42fe3c296dea6abec8c
2. https://github.com/tumashu/ivy-posframe/commit/ada1dbab9bb203207586e2f6d359b4949602e50f

**Comment by tumashu** [comment]
https://github.com/ch11ng/exwm/issues/550#issuecomment-816361564

**Comment by yantar92** [comment]
After 11085c3, I am getting the following (not always, but for some specific window configuration):

    Debugger entered--Lisp error: (args-out-of-range 0 1 1)
      (posframe--get-font-height 10804336)
      (posframe-show #<buffer *Select Link*> :poshandler posframe-poshandler-frame-center :foreground-color "#000000000000" :background-color "#b5d0ff" :internal-border-width 20)
      (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive)))
      (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))
      (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let ((l (car --dolist-tail--))) (cond ((not ...) (insert ...)) ((match-end 2) (insert ...)) (t (insert ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*"))))
      (unwind-protect (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let ((l ...)) (cond (... ...) (... ...) (t ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))) (set-window-configuration wconfig))
      (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let (...) (cond ... ... ...) (setq --dolist-tail-- ...))))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))) (set-window-configuration wconfig)))
      (save-excursion (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let ... ... ...)))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground ...) :background-color (face-background ...) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))) (set-window-configuration wconfig))))
      (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero (1+ nth) nth))) (setq link (nth (if have-zero nth (1- nth)) links))) (t (save-excursion (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer (set-buffer ...) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ... ...)) (unwind-protect (progn ... ... ...) (and ... ...))) (set-window-configuration wconfig)))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn (setq nth (1+ nth)))) (if (and (integerp nth) (>= (length links) nth)) nil (user-error "Invalid link selection")) (setq link (nth (1- nth) links)))))
      (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons (match-string-no-properties 0 zero) links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let ((save-match-data-internal (match-data))) (unwind-protect (progn (eq ... ...)) (set-match-data save-match-data-internal 'evaporate))) nil (setq links (cons (match-string-no-properties 0) links)))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t (org-attach-dir)))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links (cons "[[elisp:(org-attach-open)][Open attachment]]" links))) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero (1+ nth) nth))) (setq link (nth (if have-zero nth (1- nth)) links))) (t (save-excursion (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer ... ... ... ...) (unwind-protect ... ...)) (set-window-configuration wconfig)))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn (setq nth (1+ nth)))) (if (and (integerp nth) (>= (length links) nth)) nil (user-error "Invalid link selection")) (setq link (nth (1- nth) links))))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end))
      (save-restriction (widen) (goto-char marker) (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons (match-string-no-properties 0 zero) links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let ((save-match-data-internal ...)) (unwind-protect (progn ...) (set-match-data save-match-data-internal ...))) nil (setq links (cons (match-string-no-properties 0) links)))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t (org-attach-dir)))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links (cons "[[elisp:(org-attach-open)][Open attachment]]" links))) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero (1+ nth) nth))) (setq link (nth (if have-zero nth (1- nth)) links))) (t (save-excursion (let ((wconfig ...)) (unwind-protect (progn ... ...) (set-window-configuration wconfig)))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn (setq nth ...))) (if (and (integerp nth) (>= ... nth)) nil (user-error "Invalid link selection")) (setq link (nth (1- nth) links))))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end)))
      (save-excursion (save-restriction (widen) (goto-char marker) (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons (match-string-no-properties 0 zero) links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let (...) (unwind-protect ... ...)) nil (setq links (cons ... links)))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t (org-attach-dir)))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links (cons "[[elisp:(org-attach-open)][Open attachment]]" links))) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero ... nth))) (setq link (nth (if have-zero nth ...) links))) (t (save-excursion (let (...) (unwind-protect ... ...))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn ...)) (if (and ... ...) nil (user-error "Invalid link selection")) (setq link (nth ... links))))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end))))
      (save-current-buffer (set-buffer buffer) (save-excursion (save-restriction (widen) (goto-char marker) (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons ... links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let ... ...) nil (setq links ...))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t ...))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links ...)) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= ... ...)) (setq link (nth ... links))) (t (save-excursion (let ... ...)) (if (equal c 113) (progn ...)) (if (equal c 13) (setq link links) (setq nth ...) (if have-zero ...) (if ... nil ...) (setq link ...)))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end)))))
      (org-offer-links-in-entry #<buffer notes.org> 10804336 nil)

**Comment by tumashu** [comment]
can you provide a demo to show this bug?

在 2021-12-11 22:48:40，yantar92 ***@***.***> 写道：


After 11085c3, I am getting the following (not always, but for some specific window configuration):

Debugger entered--Lisp error: (args-out-of-range 0 1 1)
  (posframe--get-font-height 10804336)
  (posframe-show #<buffer *Select Link*> :poshandler posframe-poshandler-frame-center :foreground-color "#000000000000" :background-color "#b5d0ff" :internal-border-width 20)
  (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive)))
  (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))
  (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let ((l (car --dolist-tail--))) (cond ((not ...) (insert ...)) ((match-end 2) (insert ...)) (t (insert ...))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*"))))
  (unwind-protect (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let ((l ...)) (cond (... ...) (... ...) (t ...)) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))) (set-window-configuration wconfig))
  (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let (...) (cond ... ... ...) (setq --dolist-tail-- ...))))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground 'mode-line) :background-color (face-background 'highlight) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))) (set-window-configuration wconfig)))
  (save-excursion (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer (set-buffer (get-buffer-create "*Select Link*")) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ((--dolist-tail-- links)) (while --dolist-tail-- (let ... ... ...)))) (unwind-protect (progn (posframe-show (get-buffer "*Select Link*") :poshandler 'posframe-poshandler-frame-center :foreground-color (face-foreground ...) :background-color (face-background ...) :internal-border-width 20) (message "Select link to open, RET to open all:") (setq c (read-char-exclusive))) (and (get-buffer "*Select Link*") (kill-buffer "*Select Link*")))) (set-window-configuration wconfig))))
  (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero (1+ nth) nth))) (setq link (nth (if have-zero nth (1- nth)) links))) (t (save-excursion (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer (set-buffer ...) (erase-buffer) (insert "Select link to open, RET to open all:\n") (let ... ...)) (unwind-protect (progn ... ... ...) (and ... ...))) (set-window-configuration wconfig)))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn (setq nth (1+ nth)))) (if (and (integerp nth) (>= (length links) nth)) nil (user-error "Invalid link selection")) (setq link (nth (1- nth) links)))))
  (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons (match-string-no-properties 0 zero) links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let ((save-match-data-internal (match-data))) (unwind-protect (progn (eq ... ...)) (set-match-data save-match-data-internal 'evaporate))) nil (setq links (cons (match-string-no-properties 0) links)))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t (org-attach-dir)))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links (cons "[[elisp:(org-attach-open)][Open attachment]]" links))) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero (1+ nth) nth))) (setq link (nth (if have-zero nth (1- nth)) links))) (t (save-excursion (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-current-buffer ... ... ... ...) (unwind-protect ... ...)) (set-window-configuration wconfig)))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn (setq nth (1+ nth)))) (if (and (integerp nth) (>= (length links) nth)) nil (user-error "Invalid link selection")) (setq link (nth (1- nth) links))))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end))
  (save-restriction (widen) (goto-char marker) (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons (match-string-no-properties 0 zero) links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let ((save-match-data-internal ...)) (unwind-protect (progn ...) (set-match-data save-match-data-internal ...))) nil (setq links (cons (match-string-no-properties 0) links)))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t (org-attach-dir)))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links (cons "[[elisp:(org-attach-open)][Open attachment]]" links))) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero (1+ nth) nth))) (setq link (nth (if have-zero nth (1- nth)) links))) (t (save-excursion (let ((wconfig ...)) (unwind-protect (progn ... ...) (set-window-configuration wconfig)))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn (setq nth ...))) (if (and (integerp nth) (>= ... nth)) nil (user-error "Invalid link selection")) (setq link (nth (1- nth) links))))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end)))
  (save-excursion (save-restriction (widen) (goto-char marker) (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons (match-string-no-properties 0 zero) links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let (...) (unwind-protect ... ...)) nil (setq links (cons ... links)))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t (org-attach-dir)))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links (cons "[[elisp:(org-attach-open)][Open attachment]]" links))) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= (length links) (if have-zero ... nth))) (setq link (nth (if have-zero nth ...) links))) (t (save-excursion (let (...) (unwind-protect ... ...))) (if (equal c 113) (progn (user-error "Abort"))) (if (equal c 13) (setq link links) (setq nth (- c 48)) (if have-zero (progn ...)) (if (and ... ...) nil (user-error "Invalid link selection")) (setq link (nth ... links))))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end))))
  (save-current-buffer (set-buffer buffer) (save-excursion (save-restriction (widen) (goto-char marker) (let ((cnt 48) have-zero end links link c) (if (and (stringp zero) (string-match org-link-bracket-re zero)) (progn (setq links (cons ... links)) (setq cnt (1- cnt) have-zero t))) (save-excursion (org-back-to-heading t) (setq end (save-excursion (outline-next-heading) (point))) (while (re-search-forward org-link-any-re end t) (if (let ... ...) nil (setq links ...))) (setq links (org-uniquify (reverse links)))) (let* ((attach-dir (and t ...))) (if attach-dir (if (directory-empty-p attach-dir) nil (setq links ...)) nil)) (cond ((null links) (message "No links")) ((equal (length links) 1) (setq link (car links))) ((and (integerp nth) (>= ... ...)) (setq link (nth ... links))) (t (save-excursion (let ... ...)) (if (equal c 113) (progn ...)) (if (equal c 13) (setq link links) (setq nth ...) (if have-zero ...) (if ... nil ...) (setq link ...)))) (if (string= link "[[elisp:(org-attach-open)][Open attachment]]") (progn (setq link nil))) (cons link end)))))
  (org-offer-links-in-entry #<buffer notes.org> 10804336 nil)


—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yantar92** [comment]
> can you provide a demo to show this bug?

Sorry, that was actually unrelated to the commit I blamed. The error was
triggered by an open empty (no text, no whitespace) buffer.
